### DISCUSSION TITLE
Using noop-server to validate an Nginx configuration under load

### DISCUSSION THREAD

**Discussion by jmervine** [jmervine/noop-server#8] [General]
An example use-case for [noop-server][1] could be to validate an Nginx configuration under high load.

In this example, I use [Docker Compose][3] to build out a "one button" test, which uses [github.com/jmervine/noop-client][2] to generate load on [Nginx][4]. Nginx is then configured to load balance across multiple backends, which are all instances of noop-server.

> Note: The main reason I'm using multiple instances of the server here is because in docker-compose "noop-server" cannot handle the load coming from the client and Nginx as a proxy. I believe this to be caused by Docker Compose, and not the server itself. When running this same test, with a single server, client and Nginx instance all on my local machine, the pipeline handles it with ease.

## Setup

Below I'll cover the configuration used to build this test. It includes an `nginx.conf`, `script.txt` (for "noop-client") and the `compose.yaml` file for Docker Compose. When done the setup directory should look like this:

```
.
├── compose.yaml
├── nginx.conf
└── script.txt
```

### Docker Compose Setup

As mentioned, I set up multiple instances of "noop-server" as backends, all with different ports. Nginx is configured to copy in a configuration file from local disk (shown below) and "noop-client" copies a script file (also shown below) from local disk. These services are configured to connection to each other: `client -> nginx -> servers`.
```
# file: compose.yaml
services:
  noop_server0:
    image: jmervine/noop-server:v1.3.0
    environment:
    - ADDR=0.0.0.0
    - PORT=3000
    ports:
    - "3000"

  noop_server1:
    image: jmervine/noop-server:v1.3.0
    environment:
    - ADDR=0.0.0.0
    - PORT=3001
    ports:
    - "3001"

  noop_server2:
    image: jmervine/noop-server:v1.3.0
    environment:
    - ADDR=0.0.0.0
    - PORT=3002
    ports:
    - "3002"

  noop_server3:
    image: jmervine/noop-server:v1.3.0
    environment:
    - ADDR=0.0.0.0
    - PORT=3003
    ports:
    - "3003"

  nginx_proxy:
    image: nginx:latest
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
    - NGINX_PORT=80
    links:
      - "noop_server0"
      - "noop_server1"
      - "noop_server2"
      - "noop_server3"
    ports:
    - "8000:80"

  noop_client:
    image: jmervine/noop-client:latest
    command: --script=/tmp/script.txt
    links:
      - "nginx_proxy:nginx"
    volumes:
      - ./script.txt:/tmp/script.txt
```

### Nginx Setup

Beyond what you see in the above configuration, Nginx is configured to load balance to the configured backends.

Now obviously this configuration is too simple to really validate anything within Nginx, but it gives a framework for out a more complete test, with your configuration dropped in.

```
#file: nginx.conf
user  root;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;

    keepalive_timeout  65;

    # Required for docker-compose
    upstream backend {
      least_conn;
      server noop_server0:3000;
      server noop_server1:3001;
      server noop_server2:3002;
      server noop_server3:3003;
    }

    server {
        listen 0.0.0.0:8000;
        server_name nginx_proxy;

        location / {
            proxy_pass http://backend/proxied$request_uri;
        }
    }
}
```

### "noop-client" Setup

The client is setup is simple, it runs five connections, 200,000 each, to Nginx with no delay.

> Note: At the time of writing this, "noop-client" is still in development and not super stable. Specific updates were made for this test and the version used works for this use-case. That said, I do my best to push working versions and will tag the first fully tested and stable version once I'm happy with it.

```
# file: script.txt
200000|GET|http://nginx:8000/request1||0
200000|GET|http://nginx:8000/request2||0
200000|GET|http://nginx:8000/request3||0
200000|GET|http://nginx:8000/request4||0
200000|GET|http://nginx:8000/request5||0
```

## Results

The test posted ideal results under (mostly) ideal configurations, albeit a quite a bit slower that I'd hopped. For example, when running direct from client to server on my local machine (and without Docker) the test completes in about 45 seconds. 

![Screenshot 2024-04-18 at 00 52 57](https://github.com/jmervine/noop-server/assets/837893/4f7070b0-5d42-478c-85cd-e58c51c2f553)

[1]: https://github.com/jmervine/noop-server
[2]: https://github.com/jmervine/noop-client
[3]: https://docs.docker.com/compose/
[4]: https://www.nginx.com/
